#!/bin/zsh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

if [ $# -eq 0 ]; then
    echo "Uso: $0 <archivo.kt>"
    exit 1
fi

filename=$(basename "$1" .kt)

rm -rf ./$filename.jar

kotlinc "$1" -include-runtime -d "$filename.jar"

if [ $? -eq 0 ]; then
    echo "${GREEN}Compiled Kotlin code ✅${NC}"

    java -jar "$filename.jar"

    rm -f ./$filename.jar
    echo "${GREEN}JAR file cleaned 🧹${NC}"
else
    echo "${RED}Error al compilar${NC}"
fi
