name: Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo        
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"          

      - name: Verify formatting      
        run: uvx ruff format Python/
